# Generated by Django 2.2.4 on 2019-11-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsapp', '0004_auto_20191031_2038'),
        ('userapp', '0002_auto_20191030_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('oIsPay', models.BooleanField(default=False)),
                ('oaddress', models.CharField(max_length=100)),
                ('odate', models.DateField(auto_now=True)),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsInfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderInfo')),
            ],
        ),
    ]
