# Generated by Django 2.2.4 on 2019-11-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20191103_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='odate',
            field=models.DateField(auto_now=True),
        ),
    ]
