# Generated by Django 2.2.4 on 2019-10-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20191030_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.TypeInfo'),
        ),
    ]
