# Generated by Django 2.2.4 on 2019-10-30 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('upwd', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=30)),
                ('recver', models.CharField(max_length=10, null=True)),
                ('upostal', models.CharField(max_length=6, null=True)),
                ('uphone', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=20, null=True)),
                ('uaddrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uaddrs', to='userapp.UserInfo')),
                ('ushipaddrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ushipaddrs', to='userapp.UserInfo')),
            ],
        ),
    ]
