# Generated by Django 2.2.4 on 2019-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
